[2024-09-29T09:15:02.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T09:15:02.682+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-09-29T09:15:02.702+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-09-29T09:15:02.703+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T09:15:02.745+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-06-24 00:00:00+00:00
[2024-09-29T09:15:02.765+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=35164) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T09:15:02.769+0000] {standard_task_runner.py:63} INFO - Started process 35252 to run task
[2024-09-29T09:15:02.773+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_dataset', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '797', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpx_c7ts7x']
[2024-09-29T09:15:02.774+0000] {standard_task_runner.py:91} INFO - Job 797: Subtask create_dataset
[2024-09-29T09:15:02.915+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_dataset scheduled__2024-06-24T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T09:15:03.089+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-09-29T09:15:03.091+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T09:15:03.103+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T09:15:03.112+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-09-29T09:15:03.173+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value finalproject_data.
[2024-09-29T09:15:03.174+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value madt-finalproject.
[2024-09-29T09:15:03.174+0000] {bigquery.py:481} INFO - Creating dataset: finalproject_data in project: madt-finalproject 
[2024-09-29T09:15:03.563+0000] {bigquery.py:2045} INFO - Dataset finalproject_data already exists.
[2024-09-29T09:15:03.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T09:15:03.595+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dataset, execution_date=20240624T000000, start_date=20240929T091502, end_date=20240929T091503
[2024-09-29T09:15:03.642+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T09:15:03.704+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-09-29T09:15:03.713+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
